#!/bin/bash


# Set decoration geometry
berryc border_width       2
berryc inner_border_width 0
berryc title_height       30
berryc top_gap            30

# Set decoration colors
berryc focus_color         181825
berryc unfocus_color       1e1e2e
berryc inner_focus_color   74C7EC
berryc inner_unfocus_color 1e1e2e
berryc text_focus_color    1e1e2e
berryc text_unfocus_color  bac2de

# Other options
berryc smart_place "true"
berryc draw_text   "true"
berryc edge_lock   "false"
berryc set_font    "Dina-9"


xcape -e 'Super_L=Super_L|space' &
nitrogen --restore &
jgmenu --at-pointer &
sxhkd -c ~/.config/berry/sxhkdrc &
#xcompmgr -c -C -t-5 -l-5 -r4.2 -o.55 &
xcompmgr &
#plank &
polybar &
dunst
#nitrogen --restore

